# Configuration for flavours
# https://github.com/Misterio77/flavours
#
# Example config and default values
#
# [[item]]
# file = '~/.config/example' (file to inject to, supports tilde and env var expansion. required)
# template = 'example' (template to use. required)
# subtemplate = 'default' (subtemplate to use)
# rewrite = false (should we rewrite the entire file?)
# start = '# Start flavours' (if not rewriting, where to start replacing)
# end = '# End flavours' (if not rewriting, where to stop replacing)
# hook = '' (command to execute after injecting)
#
# Example for i3
#
# [[item]]
# file = '~/.config/i3/config'
# template = 'i3'
# subtemplate = 'colors'
# hook = 'i3-msg reload'
# rewrite = false

[[item]]
file = '~/.config/termite/config'
template = 'termite'
rewrite = false
start= '# Start flavours'
end = '# End flavours'
hook = 'killall -USR1 termite'

[[item]]
file = '~/.config/nvim/colors/base16.vim'
template = 'vim'
rewrite = false
start= '" Start flavours'
end = '" End flavours'

[[item]]
file = '~/.Xresources'
template = 'xresources'
rewrite = false
start= '/* Start flavours */'
end = '/* End flavours */'
hook = 'bash -c "xrdb -override ~/.Xresources; killall -USR1 polybar; bspc wm -r"'

[[item]]
file = '~/.config/rofi/themes/colors.rasi'
template = 'rofi'
subtemplate = 'colors'
rewrite = true
