#!/bin/sh

# start hot-key daemon
sxhkd &

# start polybar
polybar main &

# set wallpaper
feh --no-fehbg --bg-fill --randomize $HOME/.local/share/backgrounds/*

# set compositor for shadows and stuff
picom &

wmname LG3D &
