#! /bin/sh

# load colors
bspwm_colors &

# set up HDMI if connected
intern=LVDS1
extern=HDMI1

bspc monitor $intern -d 1 2 3 4 5 6 7

if xrandr | grep "$extern connected" ;
then
	xrandr --output "$extern" --mode 1920x1080 --left-of $intern
	bspc monitor $extern -d 8
    bspc monitor LVDS1 -s HDMI1
fi


# make window focus follow mouse
bspc config focus_follows_pointer true

# for spiral mode
bspc config automatic_scheme spiral

bspc config border_width	2
bspc config window_gap		3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config ignore_ewmh_focus true
bspc config ignore_ewmh_fullscreen all
bspc config honor_size_hints false

bspc rule -a ffplay desktop='^7' state=fullscreen follow=on
bspc rule -a helipad state=pseudo_tiled rectangle=1150x470+0+0 sticky=on hidden=on
bspc rule -a Brave-browser desktop='^2'
bspc rule -a Brave state=floating rectangle=900x470+0+0
bspc rule -a ranger desktop='^3' state=pseudo_tiled rectangle=1150x500+0+0 follow=on
bspc rule -a mpv state=floating follow=on rectangle=1166x568+100+100
bspc rule -a Gimp-2.10 desktop='^4' state=floating follow=on
