#!/bin/sh

function desktops {
    local i=0
    local m
    for m in $(bspc query -M)
    do
        bspc monitor $m -d $(seq -s" " $((i+1)) $((i+5)))
        $((i+=5))
    done
}

## Coloring
FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')

desktops

bspc config normal_border_color "$BLACK"
bspc config active_border_color "$MAGENTA"
bspc config focused_border_color "$MAGENTA"
bspc config presel_feedback_color "$RED" 

bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

# for spiral mode
bspc config automatic_scheme spiral

bspc config border_width	2
bspc config window_gap		3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config ignore_ewmh_focus true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

scratchpad_size=$(bspc wm -d | jq -r '.monitors[0].rectangle | "\(.width)x\(.height/(5/2) | round)"')
bspc rule -a scratchpad layer=above sticky=on state=floating hidden=on border=off rectangle=$scratchpad_size+0+0

# check scratchpad already running
[ "$(ps -x | grep -c 'scratchpad')" -eq "1" ] && $TERMINAL --class=scratchpad -e scratch &

# start hot-key daemon
sxhkd &

# set compositor for shadows and stuff
picom &

# set wallpaper
feh --no-fehbg --bg-fill $WALLPAPER

# start polybar
polybar -r main &

# apply gtk themes
xsettingsd &
