#! /bin/sh

sxhkd &

# set up HDMI if connected
intern=LVDS1
extern=HDMI1

if xrandr | grep "$extern connected"; then
    xrandr --output "$extern" --auto --left-of $intern
    bspc monitor HDMI1 -d 8 9
fi


# start helipad
[[ -z "$(xdotool search --class helipad)" ]] && $TERMINAL --class=helipad &

# set wallpaper
feh --randomize --bg-scale ~/.local/share/backgrounds/*

# set compositor for shadows and stuff
picom &



# make window focus follow mouse
bspc config focus_follows_pointer true

# for spiral mode
bspc config automatic_scheme spiral

bspc monitor LVDS1 -d 1 2 3 4 5 6 7

bspc config border_width	2
bspc config window_gap		10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config ignore_ewmh_focus true
bspc config ignore_ewmh_fullscreen all
bspc config honor_size_hints false

bspc rule -a lock desktop='^7' state=fullscreen follow=on
bspc rule -a helipad state=pseudo_tiled rectangle=1200x675+0+0 sticky=on hidden=on
#bspc rule -a Termite state=pseudo_tiled rectangle=1066x470+0+0
bspc rule -a Brave-browser desktop='^2'
bspc rule -a Brave state=floating rectangle=900x470+0+0
bspc rule -a XTerm desktop='^3' state=pseudo_tiled rectangle=1066x470+0+0 follow=on
bspc rule -a vlc desktop='^3' state=pseudo_tiled rectangle=1066x470+0+0 follow=on
bspc rule -a Gimp-2.10 desktop='^3' state=floating follow=on
